# Build Stage
FROM node:18-alpine as builder

WORKDIR /app

COPY package*.json ./

# Use ci for reproducible builds
RUN npm ci --silent

COPY . .

RUN npm run build

# Production Stage
FROM nginx:stable-alpine

# Copy custom nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy built assets
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
